### ISSUE TITLE
Null reference check on fields.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Hyperfoil#74] opened 2019-12-06 18:23 UTC
To avoid filling the agent log files with NullPointerException messages the field httpRequest.method needs checking. Adding one more null check avoids this.

> 17:24:43,556 WARN  (nioEventLoopGroup-2-1) [i.h.c.c.n.Http1xConnection] Exception in Http1xConnection{/192.168.0.30:56111 -> aa20ba69-a86e-4294-981b-41cd258aff47.benchmark.benchserver7.perf.lab.eng.rdu2.redhat.com/192.168.0.110:80, size=1} java.lang.NullPointerException
>         at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.channelRead(Http1xRawBytesHandler.java:102)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
>         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
>         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
>         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
>         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>         at java.base/java.lang.Thread.run(Thread.java:834)
>

**Comment by whitingjr** [comment] 2019-12-06 18:50
Plus an additional null reference checks will avoid this
18:29:27,294 WARN  (nioEventLoopGroup-2-1) [i.h.c.c.n.Http1xConnection] Exception in Http1xConnection{/192.168.0.30:19906 -> aa20ba69-a86e-4294-981b-41cd258aff47.benchmark.benchserver7.perf.lab.eng.rdu2.redhat.com/192.168.0.110:80, size=1} java.lang.NullPointerException
        at io.hyperfoil.core.client.netty.BaseRawBytesHandler.invokeHandler(BaseRawBytesHandler.java:40)
        at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.passFullBuffer(Http1xRawBytesHandler.java:243)
        at io.hyperfoil.core.client.netty.Http1xRawBytesHandler.channelRead(Http1xRawBytesHandler.java:161)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by rvansa** [comment] 2019-12-09 08:54
Thanks for the report. It's not really just about putting in the checks; the request is in invalid state (not initialized) while it's in the connection's queue. I have to figure out why that happens and fix the cause.

**Comment by rvansa** [comment] 2019-12-09 13:45
Now I've noticed that this happens right after `#490 Request timeout on connection ...`, so that shows us that probably there are some bytes coming after we've cancelled the request.

**Comment by whitingjr** [comment] 2019-12-16 11:56
Ok ,so we know what's the cause. But what's being done to stop the NullPointerException messages getting logged ?

**Comment by rvansa** [comment] 2019-12-16 14:02
I wouldn't say that we now. I've just noticed that it might be relevant.
We need to get a trace log / debug why the bytes are coming event though the connection should be cancelled = closed, and fix the root cause.

**Comment by rvansa** [comment] 2020-03-27 15:26
Closing my this until we get a new occurrence.

**Closed by rvansa** 2020-03-27 15:26 UTC
