### ISSUE TITLE
Provide support for gRPC

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#133] opened 2020-12-09 08:40 UTC
gRPC is a popular mechanism for implementing remote endpoints. Providing support for invoking gRPC endpoints would allow a larger range of applications to be tested with Hyperfoil

**Comment by rvansa** [comment] 2020-12-09 08:48
It seems that [gRPC Java](https://github.com/grpc/grpc-java) does a lot of work in generated subs. That would be hard to reuse by Hyperfoil since it shouldn't generate any Java code (and compile it) from the proto files. Hyperfoil benchmark file should just link the proto files and then fill the data from YAML, so HF would keep a generic representation of the message and it might need to serialize it itself.

**Comment by rvansa** [comment] 2020-12-09 08:50
Actually we might use https://github.com/infinispan/protostream for the serialization part.

**Comment by lampajr** [comment] 2024-08-07 16:23
Closing as duplicate of https://github.com/Hyperfoil/Hyperfoil/issues/281 (keeping the other one as it has more comments and discussions)

**Closed by lampajr** 2024-08-07 16:23 UTC
Labels: enhancement
