### ISSUE TITLE
CLI export generates invalid json

### ISSUE THREAD

**Issue by mocenas** [Hyperfoil/Hyperfoil#191] opened 2021-08-31 10:03 UTC
Using hyperfoil 0.16 and it's CLI and local server, it often generates an invalid json output. I'm attaching both scenario and output in generated. 
Way I use it, is simply starting cli and continuing `start-local,  upload, run , export`. This problem does not happen consistently (can't reliably reproduce), but happens quite often.

Quickly analysing the json output, it seems that exporter just stopped in the middle of `stats` section - not even finishing the section to be syntactically valid. No further sections like `sessions, agents, ...` are present at all.

Export itself happens quickly ( < 1 sec) and no problem is logged in the cli. Also run seems to finish without problem.
[scenario_and_output.zip](https://github.com/Hyperfoil/Hyperfoil/files/7082997/scenario_and_output.zip)

**Comment by rvansa** [comment] 2021-08-31 11:32
Thanks for reporting, can you see anything in the controller log? My wild guess would be some NPE/ArrayOutOfBounds or something similar happening when the JSON is generated.

**Comment by mocenas** [comment] 2021-08-31 12:28
No console looks completely OK, no sign of a problem. I've did another run, with same problem, and this time output is much smaller and it seems it stopped in writing in the middle of single json object. (attaching [output.zip](https://github.com/Hyperfoil/Hyperfoil/files/7083892/output.zip))

**Comment by rvansa** [comment] 2021-08-31 12:37
Could you check if the JSON that get automatically written to the run directory (by default `/tmp/hyperfoil/runs/XXXX/all.json`) looks correct?

**Comment by mocenas** [comment] 2021-08-31 12:50
Yes file in `/tmp/hyperfoil/../all.json` looks correct.

**Comment by rvansa** [comment] 2021-08-31 13:42
Okay, so the controller sends this file directly using Vert.x `sendFile` method. On the other side the `export` command should get all-or-nothing and dump it into the file using `Files.write(path, bytes)`.
Since you state that the file on controller is consistent, I suppose you could reproduce this in some invocations of the `export` command, and not in others. It would be useful if you could `curl localhost:8090/run/XXXX/stats/all -H 'Accept: application/json' -v ` and see if you have incomplete output in there, and if this is using transfer-encoding, if content-length matches actual output etc...

**Comment by mocenas** [comment] 2021-09-01 11:06
I tried to export the same output another time - in a new local server. And the exported file is actually OK.
I tried to `curl` the localhost server and it also worked - `content-type` and `content-length` match the file and the response text seems to be full file.
But again - this was tested on a new instance of a local server.

**Comment by rvansa** [comment] 2021-09-07 12:44
Closing as non-reproducible. Please reopen if you have further trouble, ideally with more info.

**Closed by rvansa** 2021-09-07 12:44 UTC
